### ISSUE TITLE
Feat/ Event registration form

### ISSUE THREAD

**Issue by shyam-patel-kira** [zenbitETH/Zenbit-Badges#14] opened 2024-06-25 17:44 UTC
- [ ] UI for form with custom form creation similar to what we have for Quiz
- [ ] store this on the database
- [ ] map this to an eventId

**Comment by Markkos89** [comment] 2024-06-26 23:00
![image](https://github.com/zenbitETH/Zenbit-Badges/assets/2791028/0f84ff3e-679c-48c7-87ea-143b0bc99037)



- Map `eventDate` field from the database to the `EventCards` from the root page and validate if the vent has not started yet, then the user will have to be able to **register** to the event. 
- Modifiy the hover action of the `EventCard`so when the event has not started yet, the user by clicking in the card will be redirected to the ** new register form** ( take in consideration that if the event is ongoing the message should say the actual "conecta tu cartera web3", if the event hasn't started yet, the message should say "Reserva tu lugar" )

- For the scenario where the participant has already rtegister for the first event, the _participant document_ will be already created. So, after the first event, if the participant register for more events, we have to validate in the backend with the key field `email` to not create a duplicate of the _participant document_ and in this cases we will have to add the actual eventID to the `eventsIDs` array in the corresponding _participants document_ 

- The new REGISTER FORM will have to populate the next fields: Participant Name, Participant Email and the Particpant Organization and we have to store this information in the db properly as explained above.

_Note: Once the participant creates his wallet for first time we have to store the wallet address in the db properly. This will be the key field to make the relation to capture usefull information about the participant assistance and other metrics_

**Closed as completed** 2024-08-06 16:28 UTC
Labels: enhancement
